spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
ai.service.url=http://127.0.0.1:8000/analyze
spring.datasource.username=postgres
spring.datasource.password=pragnya21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.jpa.open-in-view=false
